version: '3.8'

# Override para desarrollo con hot reload
services:
  # Servidor en modo desarrollo
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev

  # Cliente en modo desarrollo
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    command: npm run dev
